#!/bin/bash

./shipicon.py --shiplist=ss_list.txt --shipclass=submarine
./shipicon.py --shiplist=dd_list.txt --shipclass=destroyer
./shipicon.py --shiplist=ca_list.txt --shipclass=cruiser
./shipicon.py --shiplist=bb_list.txt --shipclass=battleship
./shipicon.py --shiplist=cv_list.txt --shipclass=aircarrier
